language: ruby
rvm:
  - 2.2.4
  - 2.3.0
gemfile:
  - gemfiles/Gemfile-5-0
  - gemfiles/Gemfile-5-0-1
  - gemfiles/Gemfile-5-1
  - gemfiles/Gemfile-edge
matrix:
  allow_failures:
    - gemfile: gemfiles/Gemfile-edge
script:
  - bundle exec rake test
  - bundle exec rubocop
